name: Gerar Instalador ViewSync (Apenas Mac)

on:
  workflow_dispatch:

jobs:
  build-mac:
    name: Build para Mac
    runs-on: macos-latest

    steps:
      - name: 📥 Baixando o seu código
        uses: actions/checkout@v4

      - name: ⚙️ Configurando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 📦 Instalando as dependências (Motor Apple)
        run: npm install --no-package-lock

      - name: 🏗️ Compilando o Viewer (Site do Aluno)
        run: |
          cd apps/viewer-web
          npm run build

      - name: 🚚 Movendo a pasta 'out' para o Desktop
        run: mv apps/viewer-web/out apps/desktop-transmissor/out

      - name: 🍎 Gerando .DMG (Mac)
        run: |
          cd apps/desktop-transmissor
          npm run build -- --mac

      - name: 💾 Salvando o Arquivo Final
        uses: actions/upload-artifact@v4
        with:
          name: ViewSync-Instalador-Mac
          path: apps/desktop-transmissor/release/*.dmg